In [41]:
from google.colab import files
uploaded = files.upload()

Saving Rental_Asset_Dataset.csv to Rental_Asset_Dataset (1).csv

In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv("Rental_Asset_Dataset.csv")
df.head()

,Asset ID,Asset Type,Vendor Name,Monthly Rent,Asset Purchase Cost,Date of Acquisition,Assigned Employee ID,Current Status,Usage Days (last 30),City,Monthly Revenue per Asset
0,AST0001,Guitar,vendor a,1915.0,15486,2022-04-16,EMP893,active,1,Jaipur,1588
1,AST0002,Gopro,VendorB,NaN,18335,2023-07-17,EMP887,IN repair,2,Delhi,3012
2,AST0003,Gopro,vendor a,2623.0,31364,2022-03-22,EMP162,active,22,Delhi,2547
3,AST0004,Gopro,VendorB,3574.0,47259,2022-05-13,EMP598,active,22,Mumbai,1294
4,AST0005,Laptop,VendorB,2782.0,33576,2022-05-18,EMP645,active,11,Delhi,2985

In [44]:
df.shape

(205, 11)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Asset ID                     205 non-null    object
 1   Asset Type                   205 non-null    object
 2   Vendor Name                  185 non-null    object
 3   Monthly Rent                 184 non-null    float64
 4   Asset Purchase Cost          205 non-null    int64
 5   Date of Acquisition          205 non-null    object
 6   Assigned Employee ID         205 non-null    object
 7   Current Status               205 non-null    object
 8   Usage Days (last 30)         205 non-null    int64
 9   City                         191 non-null    object
 10  Monthly Revenue per Asset    205 non-null    int64
dtypes: float64(1), int64(3), object(7)
memory usage: 17.7+ KB

In [46]:
df.describe(include='all')

,Asset ID,Asset Type,Vendor Name,Monthly Rent,Asset Purchase Cost,Date of Acquisition,Assigned Employee ID,Current Status,Usage Days (last 30),City,Monthly Revenue per Asset
count,205,205,185,184.000000,205.000000,205,205,205,205.000000,191,205.000000
unique,200,5,3,NaN,NaN,180,179,4,NaN,11,NaN
top,AST0031,Guitar,vendor a,NaN,NaN,2022-04-21,EMP830,active,NaN,Jaipur,NaN
freq,2,45,65,NaN,NaN,3,3,146,NaN,33,NaN
mean,NaN,NaN,NaN,2404.690217,30772.804878,NaN,NaN,NaN,14.517073,NaN,3316.565854
std,NaN,NaN,NaN,936.372589,11406.665153,NaN,NaN,NaN,8.582126,NaN,1458.477726
min,NaN,NaN,NaN,804.000000,10009.000000,NaN,NaN,NaN,0.000000,NaN,1001.000000
25%,NaN,NaN,NaN,1628.750000,20975.000000,NaN,NaN,NaN,7.000000,NaN,1917.000000
50%,NaN,NaN,NaN,2430.500000,31545.000000,NaN,NaN,NaN,15.000000,NaN,3204.000000
75%,NaN,NaN,NaN,3282.000000,39189.000000,NaN,NaN,NaN,22.000000,NaN,4530.000000
max,NaN,NaN,NaN,3971.000000,49764.000000,NaN,NaN,NaN,30.000000,NaN,5969.000000

In [47]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['asset_id', 'asset_type', 'vendor_name', 'monthly_rent',
       'asset_purchase_cost', 'date_of_acquisition', 'assigned_employee_id',
       'current_status', 'usage_days_(last_30)', 'city',
       'monthly_revenue_per_asset'],
      dtype='object')

In [48]:
print("Duplicates:", df.duplicated().sum())

Duplicates: 3

In [49]:
df.drop_duplicates(inplace=True)
print("Duplicates:", df.duplicated().sum())

Duplicates: 0

In [50]:
df.isnull().sum()

asset_id                      0
asset_type                    0
vendor_name                  20
monthly_rent                 21
asset_purchase_cost           0
date_of_acquisition           0
assigned_employee_id          0
current_status                0
usage_days_(last_30)          0
city                         14
monthly_revenue_per_asset     0
dtype: int64

In [64]:
df['vendor_name'] = df['vendor_name'].fillna('Unknown Vendor')
df['monthly_rent'] = pd.to_numeric(df['monthly_rent'], errors='coerce')
df['monthly_rent'] = df['monthly_rent'].fillna(df['monthly_rent'].median())

df['city'] = df['city'].astype(str).str.strip()
df['city'] = df['city'].replace(['', 'nan', 'NaN', 'None'], np.nan)
df['city'] = df['city'].fillna('Unknown City')

In [65]:
df.isnull().sum()

asset_id                     0
asset_type                   0
vendor_name                  0
monthly_rent                 0
asset_purchase_cost          0
date_of_acquisition          0
assigned_employee_id         0
current_status               0
usage_days_(last_30)         0
city                         0
monthly_revenue_per_asset    0
monthly_profit               0
dtype: int64

In [53]:
df['vendor_name'] = df['vendor_name'].str.strip().str.title()
print(df['vendor_name'].unique())

['Vendor A' 'Vendorb' 'Vendorc' 'Unknown Vendor']

In [54]:
df['vendor_name'] = df['vendor_name'].replace({
    'Vendorb': 'Vendor B',
    'Vendorb ': 'Vendor B',
    'Vendor A ': 'Vendor A',
    # Add more if needed
})
print(df['vendor_name'].unique())

['Vendor A' 'Vendor B' 'Vendorc' 'Unknown Vendor']

In [55]:
print(df['current_status'].unique())

[' active ' 'IN repair' 'Lost' 'Returned']

In [56]:
df['current_status'] = df['current_status'].str.strip().str.lower()
print(df['current_status'].unique())

['active' 'in repair' 'lost' 'returned']

In [57]:
df['current_status'] = df['current_status'].replace({
    'in repair': 'In Repair',
    'active': 'Active',
    'retired': 'Retired',
    'returned': 'Returned'
})
print(df['current_status'].unique())

['Active' 'In Repair' 'lost' 'Returned']

In [58]:
df['monthly_revenue_per_asset'] = pd.to_numeric(df['monthly_revenue_per_asset'], errors='coerce')
df['usage_days_(last_30)'] = pd.to_numeric(df['usage_days_(last_30)'], errors='coerce')

In [59]:
df['date_of_acquisition'] = pd.to_datetime(df['date_of_acquisition'], errors='coerce')

In [66]:
df.head(20)

,asset_id,asset_type,vendor_name,monthly_rent,asset_purchase_cost,date_of_acquisition,assigned_employee_id,current_status,usage_days_(last_30),city,monthly_revenue_per_asset,monthly_profit
0,AST0001,Guitar,Vendor A,1915.0,15486,2022-04-16,EMP893,Active,1,Jaipur,1588,-327.0
1,AST0002,Gopro,Vendor B,2431.0,18335,2023-07-17,EMP887,In Repair,2,Delhi,3012,581.0
2,AST0003,Gopro,Vendor A,2623.0,31364,2022-03-22,EMP162,Active,22,Delhi,2547,-76.0
3,AST0004,Gopro,Vendor B,3574.0,47259,2022-05-13,EMP598,Active,22,Mumbai,1294,-2280.0
4,AST0005,Laptop,Vendor B,2782.0,33576,2022-05-18,EMP645,Active,11,Delhi,2985,203.0
5,AST0006,Guitar,Vendorc,1653.0,41667,2022-07-03,EMP150,Active,19,Jaipur,4117,2464.0
6,AST0007,Gaming PC,Vendor B,850.0,21130,2023-02-05,EMP439,lost,4,Delhi,2690,1840.0
7,AST0008,Gaming PC,Vendorc,1374.0,31972,2022-11-26,EMP142,In Repair,4,Jaipur,2136,762.0
8,AST0009,Laptop,Vendor A,1948.0,11167,2023-05-23,EMP769,Returned,5,Mumbai,3064,1116.0
9,AST0010,Gopro,Vendor A,2997.0,37192,2022-03-10,EMP637,Active,29,Bangalore,5455,2458.0
10,AST0011,PS5,Unknown Vendor,3161.0,11062,2023-06-30,EMP830,In Repair,8,Unknown City,5795,2634.0
11,AST0012,Laptop,Vendor A,2431.0,28540,2022-02-22,EMP486,lost,1,Bangalore,5543,3112.0
12,AST0013,Laptop,Vendorc,3152.0,34244,2023-03-26,EMP901,Active,20,Unknown City,5770,2618.0
13,AST0014,Guitar,Vendor A,2515.0,31545,2022-07-24,EMP568,Active,11,Delhi,2007,-508.0
14,AST0015,Gaming PC,Vendor B,1481.0,31689,2022-05-06,EMP577,In Repair,2,Pune,3514,2033.0
15,AST0016,Laptop,Vendor B,1637.0,21174,2022-02-12,EMP923,Active,19,Bangalore,4526,2889.0
16,AST0017,Laptop,Vendor B,1877.0,32925,2022-04-21,EMP555,In Repair,25,Delhi,5681,3804.0
17,AST0018,Gopro,Vendorc,3850.0,47497,2023-10-25,EMP790,Active,21,Unknown City,2247,-1603.0
18,AST0019,Gopro,Vendor A,3291.0,19348,2022-07-02,EMP836,In Repair,11,Delhi,4902,1611.0
19,AST0020,PS5,Vendor A,2431.0,33714,2022-04-05,EMP622,Active,23,Mumbai,2435,4.0

In [69]:
df['monthly_profit'] = df['monthly_revenue_per_asset'] - df['monthly_rent']
df.head(20)

,asset_id,asset_type,vendor_name,monthly_rent,asset_purchase_cost,date_of_acquisition,assigned_employee_id,current_status,usage_days_(last_30),city,monthly_revenue_per_asset,monthly_profit
0,AST0001,Guitar,Vendor A,1915.0,15486,2022-04-16,EMP893,Active,1,Jaipur,1588,-327.0
1,AST0002,Gopro,Vendor B,2431.0,18335,2023-07-17,EMP887,In Repair,2,Delhi,3012,581.0
2,AST0003,Gopro,Vendor A,2623.0,31364,2022-03-22,EMP162,Active,22,Delhi,2547,-76.0
3,AST0004,Gopro,Vendor B,3574.0,47259,2022-05-13,EMP598,Active,22,Mumbai,1294,-2280.0
4,AST0005,Laptop,Vendor B,2782.0,33576,2022-05-18,EMP645,Active,11,Delhi,2985,203.0
5,AST0006,Guitar,Vendorc,1653.0,41667,2022-07-03,EMP150,Active,19,Jaipur,4117,2464.0
6,AST0007,Gaming PC,Vendor B,850.0,21130,2023-02-05,EMP439,lost,4,Delhi,2690,1840.0
7,AST0008,Gaming PC,Vendorc,1374.0,31972,2022-11-26,EMP142,In Repair,4,Jaipur,2136,762.0
8,AST0009,Laptop,Vendor A,1948.0,11167,2023-05-23,EMP769,Returned,5,Mumbai,3064,1116.0
9,AST0010,Gopro,Vendor A,2997.0,37192,2022-03-10,EMP637,Active,29,Bangalore,5455,2458.0
10,AST0011,PS5,Unknown Vendor,3161.0,11062,2023-06-30,EMP830,In Repair,8,Unknown City,5795,2634.0
11,AST0012,Laptop,Vendor A,2431.0,28540,2022-02-22,EMP486,lost,1,Bangalore,5543,3112.0
12,AST0013,Laptop,Vendorc,3152.0,34244,2023-03-26,EMP901,Active,20,Unknown City,5770,2618.0
13,AST0014,Guitar,Vendor A,2515.0,31545,2022-07-24,EMP568,Active,11,Delhi,2007,-508.0
14,AST0015,Gaming PC,Vendor B,1481.0,31689,2022-05-06,EMP577,In Repair,2,Pune,3514,2033.0
15,AST0016,Laptop,Vendor B,1637.0,21174,2022-02-12,EMP923,Active,19,Bangalore,4526,2889.0
16,AST0017,Laptop,Vendor B,1877.0,32925,2022-04-21,EMP555,In Repair,25,Delhi,5681,3804.0
17,AST0018,Gopro,Vendorc,3850.0,47497,2023-10-25,EMP790,Active,21,Unknown City,2247,-1603.0
18,AST0019,Gopro,Vendor A,3291.0,19348,2022-07-02,EMP836,In Repair,11,Delhi,4902,1611.0
19,AST0020,PS5,Vendor A,2431.0,33714,2022-04-05,EMP622,Active,23,Mumbai,2435,4.0

In [70]:
df.to_csv('Cleaned_Rental_Asset_Dataset.csv', index=False)
from google.colab import files
files.download("Cleaned_Rental_Asset_Dataset.csv")